export { Home, Notifications, Email, FavoriteBorder, ExitToApp, LocationOn, Search } from 'styled-icons/material-outlined';
export { Person, Cake, Favorite } from 'styled-icons/material';
export { ArrowLeft } from 'styled-icons/heroicons-solid';
export { Chat } from 'styled-icons/heroicons-outline';
export { FileList, FileList2 } from 'styled-icons/remix-line';
export { Bookmark, Hash, Calendar } from 'styled-icons/boxicons-regular';
export { Twitter } from 'styled-icons/boxicons-logos';
export { Retweet } from 'styled-icons/fa-solid';
export { Link } from 'styled-icons/entypo';
export { RocketseatIcon as Rocketseat } from '../components/SVGcons';
export { TweetIcon as Tweet } from '../components/SVGcons';
export { DotsCircleHorizontal } from '../components/SVGcons';